<a href="https://colab.research.google.com/github/jeguns/Manipulacion-de-datos-con-R-y-Python/blob/main/Python/7%20-%20Tipos%20y%20colecciones%20de%20datos/U7_Tipos_y_estructuras_de_datos_en_Python%20-%20CLASE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tipos de datos estructurados

## Integer

In [1]:
x = 4
type(x)

int

In [2]:
isinstance(x, int)

True

In [3]:
x = 4
type(x)
isinstance(x, int)

True

In [4]:
y = 4
print(type(y)) # <class 'int'>
print(type(y).__name__) # int
print(isinstance(y, int)) # True

<class 'int'>
int
True


In [5]:
y = 4.0
print(type(y).__name__)
print(isinstance(y, int))

float
False


## Float

In [6]:
y = 40.3
type(y)

float

In [7]:
isinstance(y, int)

False

In [8]:
isinstance(y, float)

True

## Complex

In [12]:
1j # número imaginario = i = raíz cuadrada de -1

1j

In [11]:
z = 1 + 2j
type(z)

complex

In [13]:
print(isinstance(z, int))
print(isinstance(z, float))
print(isinstance(z, complex))

False
False
True


In [14]:
t = 1j
print(type(t).__name__)
print(isinstance(t, int))
print(isinstance(t, float))
print(isinstance(t, complex))

complex
False
False
True


In [15]:
w = 10 + 0j
print(type(w).__name__)
print(isinstance(w, int))
print(isinstance(w, float))
print(isinstance(w, complex))

complex
False
False
True


In [16]:
v = 10
print(type(v).__name__)
print(isinstance(v, int))
print(isinstance(v, float))
print(isinstance(v, complex))

int
True
False
False


## Booleano

In [27]:
a = True
print(type(a).__name__)
print(isinstance(a, int)) # True = 1
print(isinstance(a, float))
print(isinstance(a, complex))
print(isinstance(a, bool))

bool
True
False
False
True


In [20]:
True + 2 # True = 1

3

In [21]:
3 == 5.2 # ¿3 = 5.2?

False

In [22]:
4.6 <= 8.1

True

In [23]:
12 > 3.5

True

In [24]:
5 != 8 # != : Distinto

True

In [28]:
b <- (4 == 5)
b

False

## String

In [35]:
p = "Universidad Agraria"
print(type(p).__name__)
print(isinstance(p, int))
print(isinstance(p, float))
print(isinstance(p, complex))
print(isinstance(p, bool))
print(isinstance(p, str))

str
False
False
False
False
True


In [36]:
q = '70096321'
type(q)

str

In [37]:
s = 'Python is a programming language that lets you work quickly and integrate systems more effectively.'
type(s)

str

# Colecciones de datos

## Listas

Es una estructura de datos ordenada y **mutable** que permite almacenar una colección de elementos. Los elementos de una lista pueden ser de cualquier tipo de datos (enteros, cadenas, otros objetos) y no necesariamente deben ser del mismo tipo. Las listas en Python son muy flexibles y permiten agregar, modificar, eliminar y ordenar elementos fácilmente.



In [41]:
x1 = [3, 4, 5, 12, 3.4]
x1

[3, 4, 5, 12, 3.4]

In [42]:
type(x1)

list

In [43]:
isinstance(x1, list)

True

In [44]:
x1[0]

3

In [45]:
x1[0:3]

[3, 4, 5]

In [49]:
x1[2:] # Extrae los datos desde la posición 2

[5, 12, 3.4]

In [50]:
x1[:2] # Extrae los datos hasta antes de la posición 2 (pos 1)

[3, 4]

In [46]:
x1[:1] + x1[2:]

[3, 5, 12, 3.4]

In [55]:
x1

[3, 4, 5, 12, 3.4]

In [56]:
x1.pop(1)
x1

[3, 5, 12, 3.4]

In [57]:
x1[-1]

3.4

In [59]:
x1[-3]

5

In [60]:
x1[-3:]

[5, 12, 3.4]

In [66]:
x1.append(10)
x1

[3, 5, 12, 3.4, 10, 10, 10]

In [67]:
x1.remove(5)
x1

[3, 12, 3.4, 10, 10, 10]

In [68]:
x1.remove(10)
x1

[3, 12, 3.4, 10, 10]

In [69]:
len(x1)

5

In [70]:
x2 = [4, 5, 6]
x1 + x2

[3, 12, 3.4, 10, 10, 4, 5, 6]

In [71]:
x2 * 3

[4, 5, 6, 4, 5, 6, 4, 5, 6]

In [72]:
list(range(1, 6))

[1, 2, 3, 4, 5]

In [73]:
import numpy
numpy.arange(1, 5.25, 0.25).tolist()

[1.0,
 1.25,
 1.5,
 1.75,
 2.0,
 2.25,
 2.5,
 2.75,
 3.0,
 3.25,
 3.5,
 3.75,
 4.0,
 4.25,
 4.5,
 4.75,
 5.0]

In [74]:
import numpy as np
np.arange(1, 5.25, 0.25).tolist()

[1.0,
 1.25,
 1.5,
 1.75,
 2.0,
 2.25,
 2.5,
 2.75,
 3.0,
 3.25,
 3.5,
 3.75,
 4.0,
 4.25,
 4.5,
 4.75,
 5.0]

In [75]:
x3 = [9, 4, 2, 3, 4, 6, 7, 8 ,10, 3, 2]
x3[::-1]

[2, 3, 10, 8, 7, 6, 4, 3, 2, 4, 9]

In [76]:
x3[8:2:-2]

[10, 7, 4]

In [77]:
x3[2:8:2]

[2, 4, 7]

In [78]:
sorted(x3)

[2, 2, 3, 3, 4, 4, 6, 7, 8, 9, 10]

In [79]:
sorted(x3, reverse = True)

[10, 9, 8, 7, 6, 4, 4, 3, 3, 2, 2]

In [81]:
import string
x4 = list(string.ascii_lowercase)
x4

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [85]:
x4.index("b") + 1

2

In [86]:
x5 = [[1,2], [3,4], [5,6,7,8,9,11,15,14,18,18,20]]
x5

[[1, 2], [3, 4], [5, 6, 7, 8, 9, 11, 15, 14, 18, 18, 20]]

In [87]:
x5[0]

[1, 2]

In [88]:
x5[0][1]

2

In [92]:
x5[2][0:3]

[5, 6, 7]

In [93]:
a, b, c = [1, 5, 10]
a

1

In [94]:
b

5

## Tuplas

Una tupla en Python es una colección ordenada e *inmutable* de elementos. Esto significa que, a diferencia de las listas, una tupla no puede ser modificada (no se pueden agregar, eliminar o cambiar elementos). Las tuplas son útiles cuando necesitas almacenar un conjunto de elementos que no deberían cambiar a lo largo del tiempo. Se definen usando paréntesis.



In [95]:
y0 = 3, 4, 5, 12, 3.4
y0

(3, 4, 5, 12, 3.4)

In [96]:
y1 = (3, 4, 5, 12, 3.4)
y1

(3, 4, 5, 12, 3.4)

In [97]:
type(y1)

tuple

In [98]:
isinstance(y1, tuple)

True

In [99]:
y1[0]

3

In [100]:
y1[0:3]

(3, 4, 5)

In [101]:
y1[2:]

(5, 12, 3.4)

In [102]:
y1[:2]

(3, 4)

In [103]:
y1[:1] + y1[2:]

(3, 5, 12, 3.4)

In [104]:
y1[-1]

3.4

In [105]:
y1[-3]

5

In [106]:
y1[-3:]

(5, 12, 3.4)

In [108]:
y1

(3, 4, 5, 12, 3.4)

In [107]:
len(y1)

5

In [109]:
y2 = (4, 5, 6)
y1 + y2

(3, 4, 5, 12, 3.4, 4, 5, 6)

In [110]:
y2 * 3

(4, 5, 6, 4, 5, 6, 4, 5, 6)

In [111]:
tuple(range(1, 6))

(1, 2, 3, 4, 5)

In [112]:
import numpy as np
tuple(np.arange(1, 5.25, 0.25).tolist())

(1.0,
 1.25,
 1.5,
 1.75,
 2.0,
 2.25,
 2.5,
 2.75,
 3.0,
 3.25,
 3.5,
 3.75,
 4.0,
 4.25,
 4.5,
 4.75,
 5.0)

In [113]:
y3 = (9, 4, 2, 3, 4, 6, 7, 8, 10, 3, 2)
y3[::-1]

(2, 3, 10, 8, 7, 6, 4, 3, 2, 4, 9)

In [114]:
y3[8:2:-2]

(10, 7, 4)

In [115]:
y3[2:8:2]

(2, 4, 7)

In [116]:
tuple(sorted(x3))

(2, 2, 3, 3, 4, 4, 6, 7, 8, 9, 10)

In [117]:
tuple(sorted(x3, reverse = True))

(10, 9, 8, 7, 6, 4, 4, 3, 3, 2, 2)

In [118]:
y4 = tuple(string.ascii_lowercase)
y4

('a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z')

In [121]:
y4.index("b") + 1

2

In [122]:
y5 =  ((1, 2), (3, 4), (5, 6), [4,4,4,6])
y5

((1, 2), (3, 4), (5, 6), [4, 4, 4, 6])

In [123]:
y5[0]

(1, 2)

In [124]:
y5[0][1]

2

In [126]:
y5[3][1]

4

In [127]:
y5[3][1] = 10 # sí se puede modificar un dato dentro de una lista
y5

((1, 2), (3, 4), (5, 6), [4, 10, 4, 6])

In [128]:
y5[1][1] = 10 # no se puede modificar un dato dentro de una tupla

TypeError: 'tuple' object does not support item assignment

In [129]:
p, q, r = (1, 5, 10)
p

1

In [130]:
q

5

## Diccionarios

Un diccionario en Python es una estructura de datos que almacena pares clave-valor. Es similar a un "mapa" o "tabla de búsqueda" en la que puedes asociar una clave con un valor determinado. La clave actúa como un identificador único para acceder rápidamente al valor correspondiente. Los diccionarios son **mutables**, lo que significa que se pueden cambiar, agregar o eliminar elementos después de su creación. Se definen usando llaves {} y los pares clave-valor se separan por comas

In [132]:
z1 = {"a": 3, "b": 4, "c": 5, "d": 12, "e": 3.4}
z1

{'a': 3, 'b': 4, 'c': 5, 'd': 12, 'e': 3.4}

In [133]:
type(z1)

dict

In [134]:
isinstance(z1, dict)

True

In [135]:
z1[0] # los elementos de un diccionario no se acceden por posición, sino por clave

KeyError: 0

In [136]:
z1['a'] # o z1["a"]

3

In [137]:
for k in ["a", "b", "c"]:
  print(z1[k])

3
4
5


In [138]:
for k in z1:
    if k != "b":
        print(z1[k])

3
5
12
3.4


In [140]:
z2 = {"f": 4, "g": 5, "h": 6}
{**z1, **z2}

{'a': 3, 'b': 4, 'c': 5, 'd': 12, 'e': 3.4, 'f': 4, 'g': 5, 'h': 6}

## Arrays

Colección ordenada de elementos, similar a las listas pero más eficientes para manejar grandes cantidades de datos numéricos. Comúnmente se usan a través del módulo numpy

In [143]:
import numpy as np
m1 = np.array([3,4,5,12,3.4])
m1

array([ 3. ,  4. ,  5. , 12. ,  3.4])

In [144]:
type(m1)

numpy.ndarray

In [145]:
isinstance(m1,np.ndarray)

True

In [146]:
m1[0]

3.0

In [147]:
m1[0:3]

array([3., 4., 5.])

In [148]:
m1[2:]

array([ 5. , 12. ,  3.4])

In [149]:
m1[:2]

array([3., 4.])

In [150]:
m1[:1] +  m1[2:]

array([ 8. , 15. ,  6.4])

In [164]:
np.concatenate((m1[:1], m1[2:]))

array([ 3. ,  5. , 12. ,  3.4])

In [165]:
np.delete(m1, 1)

array([ 3. ,  5. , 12. ,  3.4])

In [167]:
m1[-1]

3.4

In [168]:
m1[-3]

5.0

In [169]:
m1[-3:]

array([ 5. , 12. ,  3.4])

In [170]:
m1.append(10) # append es exclusivo de listas

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [171]:
np.append(m1, 10)

array([ 3. ,  4. ,  5. , 12. ,  3.4, 10. ])

In [172]:
len(m1) # len es una abreviatura de length

5

In [173]:
m2 = np.array([4, 5, 6])
np.concatenate((m1, m2))

array([ 3. ,  4. ,  5. , 12. ,  3.4,  4. ,  5. ,  6. ])

In [174]:
np.tile(m2, 3)

array([4, 5, 6, 4, 5, 6, 4, 5, 6])

In [176]:
np.array(range(1, 6))

array([1, 2, 3, 4, 5])

In [175]:
np.arange(1, 5.25, 0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [178]:
m3 = np.array([9, 4, 2, 3, 4, 6, 7, 8, 10, 3, 2])
m3[::-1]

array([ 2,  3, 10,  8,  7,  6,  4,  3,  2,  4,  9])

In [183]:
np.flip(m3) # equivalente a m3[::-1]

array([ 2,  3, 10,  8,  7,  6,  4,  3,  2,  4,  9])

In [179]:
m3[8:2:-2]

array([10,  7,  4])

In [180]:
m3[2:8:2]

array([2, 4, 7])

In [181]:
np.sort(m3)

array([ 2,  2,  3,  3,  4,  4,  6,  7,  8,  9, 10])

In [182]:
np.flip(np.sort(m3))

array([10,  9,  8,  7,  6,  4,  4,  3,  3,  2,  2])

In [185]:
np.sort(m3)[::-1]

array([10,  9,  8,  7,  6,  4,  4,  3,  3,  2,  2])

In [186]:
m4 = np.array(list(string.ascii_lowercase))
m4

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='<U1')

In [192]:
np.where(m4 == "b")

(array([1]),)

In [191]:
np.where(m4 == "b")[0][0] + 1

2

In [194]:
matriz = np.array([[1, 2, 3], [1,1,111], [7, 4, 9], [10,11,12]])
matriz

array([[  1,   2,   3],
       [  1,   1, 111],
       [  7,   4,   9],
       [ 10,  11,  12]])

In [195]:
matriz[1, 2] # muestra  el dato de la segunda fila (fila en posición 1) y la tercera columna (columna en posición 2)

111

In [196]:
matriz[0,:] # muestra los datos de la primera fila (todas las columnas)

array([1, 2, 3])

In [197]:
matriz[:,1] # muestra los datos de la segunda columna (todas las filas)

array([ 2,  1,  4, 11])

In [198]:
matriz[1:3,1] # muestra los datos de la segunda y tercera fila cruzados con la segunda columna

array([1, 4])

In [202]:
matriz.ndim # número de dimensiones (2 = filas y columnas)

2

In [203]:
matriz.shape # (número de filas, número de columnas)

(4, 3)

In [204]:
matriz.size # número de filas * número de columnas

12

## Data Frames

Un DataFrame es una estructura de datos que se utiliza principalmente en pandas, una biblioteca de Python para análisis de datos. Un DataFrame es similar a una tabla en una base de datos o a una hoja de cálculo en Excel, donde los datos están organizados en filas y columnas.



In [208]:
import pandas as pd

data = {
    'Nombre': ['Ana', 'Luis', 'María','Juan'],
    'Edad': [21, 22, 20, 25],
    'Ciudad': ['Lima', 'Cusco', 'Arequipa', 'Piura']
}

d1 = pd.DataFrame(data)
d1

Nombre  Edad    Ciudad
0    Ana    21      Lima
1   Luis    22     Cusco
2  María    20  Arequipa
3   Juan    25     Piura